name: todo_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icon.jpg
    - assets/splash.jpg

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.jpg

flutter_native_splash:
  color: "#000000"
  image: assets/splash.jpg
  android_gravity: center
